

describe('Spaceship App', () => {
    // --- reset each test ---
    beforeEach(() => {
        cy.visit('http://localhost:3000/')
    })

    // --- helpers ---
    const firstNameInput = () => cy.get('input[name="first_name"]')
    const lastNameInput = () => cy.get('input[name="last_name"]')
    const emailInput = () => cy.get('input[name="email"]')
    const passwordInput = () => cy.get('input[name="password"]')
    const tosInput = () => cy.get('input[name="tos"]')
    const submitButton = () => cy.get('#submitButton')



    it('sanity checks', () => {
        expect(2*2).to.equal(4)
        expect({}).to.eql({})
    })

    it('the proper elements exist', () => {
        firstNameInput().should('exist')
        lastNameInput().should('exist')
        emailInput().should('exist')
        passwordInput().should('exist')
        tosInput().should('exist')
        submitButton().should('exist')
    })

    describe('filling out inputs and submitting correctly', () => {
        it('submit button is disabled', () => {
            submitButton().should('be.disabled')
        })
        it('can type in the input fields', () => {
            firstNameInput()
                .should('have.value', '')
                .type('Sterling')
                .should('have.value', 'Sterling')
            lastNameInput()
                .should('have.value', '')
                .type('Mount')
                .should('have.value', 'Mount')   
            emailInput()
                .should('have.value', '')
                .type('sterl@memail.com')
                .should('have.value', 'sterl@memail.com')      
            passwordInput()
                .should('have.value', '')
                .type('test123')
                .should('have.value', 'test123')      
            tosInput()
                .should('not.be.checked')
                tosInput().click()
                .should('be.checked') 
        })
        it('the submit button only enables if all of the fields are filled correctly', () => {
            submitButton().should('be.disabled')
            firstNameInput()
                .type('Sterling')
            lastNameInput()
                .type('Mount')   
            emailInput()
                .type('sterl@memail.com') 
            passwordInput()
                .type('test123')   
            submitButton().should('be.disabled') 
            tosInput().click()
            submitButton().should('not.be.disabled')
        })
        it('submitting resets the inputs', () => {
            firstNameInput()
                .type('Sterling')
            lastNameInput()
                .type('Mount')   
            emailInput()
                .type('sterl@memail.com') 
            passwordInput()
                .type('test123')   
            tosInput().click()
            submitButton().click()
            firstNameInput()
                .should('have.value', '')
            lastNameInput()
                .should('have.value', '')
            emailInput()
                .should('have.value', '')
            passwordInput()
                .should('have.value', '')   
            tosInput()
                .should('not.be.checked')     
        })
        it('submitted info appears in The Crew', () => {
            firstNameInput()
                .type('Sterling')
            lastNameInput()
                .type('Mount')   
            emailInput()
                .type('sterl@memail.com') 
            passwordInput()
                .type('test123')   
            tosInput().click()
            submitButton().click()
            cy.contains('Sterling').should('exist')
            cy.contains('Mount').should('exist')
            cy.contains('sterl@memail.com').should('exist')
        })
    })
})